APPLICATION = test_senseair
BOARD ?= lora3a-h10
RIOTBASE ?= $(CURDIR)/../RIOT
LORA3ABASE ?= $(CURDIR)/../lora3a-boards
EXTERNAL_BOARD_DIRS=$(LORA3ABASE)/boards
EXTERNAL_MODULE_DIRS=$(LORA3ABASE)/modules
EXTERNAL_PKG_DIRS=$(LORA3ABASE)/pkg
QUIET ?= 1
DEVELHELP ?= 1
PORT ?= /dev/ttyUSB0
ACMEBUS ?= 1

USEMODULE += printf_float
USEMODULE += senseair
USEMODULE += fram
USEMODULE += saml21_backup_mode


ifeq ($(ACMEBUS),1)
    CFLAGS += -DENABLE_ACME1=MODE_I2C -DSENSEAIR_I2C_DEV=ACME1_I2C_DEV -DSENSEAIR_ENABLE_PIN=GPIO_PIN\(PB,23\) -DACMEBUS_ENABLE=GPIO_PIN\(PA,28\)
else ifeq ($(ACMEBUS),2)
    CFLAGS += -DENABLE_ACME2=MODE_I2C -DSENSEAIR_I2C_DEV=ACME2_I2C_DEV -DSENSEAIR_ENABLE_PIN=GPIO_PIN\(PA,7\) -DACMEBUS_ENABLE=GPIO_PIN\(PA,31\)
else
    $(error Invalid value for ACMEBUS; should be 1 or 2)
endif

include $(RIOTBASE)/Makefile.include
